services:
  telegram-pibot-spring-postgres:
    container_name: telegram-pibot-postgres
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram-pibot
    restart: unless-stopped
